#-------------------------------------------------------------------------------------
# DockerProject - Composer 2.0
# Imagem oficial (Docker Hub): https://hub.docker.com/_/composer
#-------------------------------------------------------------------------------------

FROM composer:2.0

RUN mkdir -p /application

WORKDIR /application

CMD ["composer"]
