version: "3.1"
services:
  nginx:
    image: local/php-project:nginx119
    container_name: project-nginx
    volumes:
      - ./project:/application
    ports:
      - "1000:80"
    networks:
      - dev-network

  php-fpm:
    image: local/php-project:php80
    container_name: project-php
    volumes:
      - ./project:/application
    networks:
      - dev-network

  composer:
    image: local/php-project:composer20
    container_name: project-composer
    volumes:
      - ./project:/application
    command: composer install --ignore-platform-reqs
    networks:
      - dev-network

  mysql:
    image: local/php-project:mysql80
    container_name: project-mysql
    restart: always
    ports:
      - "1010:3306"
    networks:
      - dev-network

  phpmyadmin:
    image: local/php-project:phpmyadmin51
    container_name: project-phpmyadmin
    restart: always
    depends_on: 
      - mysql
    ports:
      - 1020:80
    networks:
      - dev-network

  rabbitmq:
    image: local/php-project:rabbitmq38
    container_name: project-rabbitmq
    ports:
      - 1030:5672
      - 1040:15672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    
networks:
  dev-network:
    driver: bridge
