#-------------------------------------------------------------------------------------
# PhpProject - Riak 2.2.3
# Imagem oficial (Docker Hub): https://hub.docker.com/basho/riak-kv
# https://github.com/basho-labs/riak-docker
# https://github.com/basho/riak-php-client
#-------------------------------------------------------------------------------------

FROM basho/riak-kv:ubuntu-2.2.3

LABEL com.basho.riak.cluster.name=riakkv

ENV CLUSTER_NAME devel

EXPOSE 8087 8098
