#-------------------------------------------------------------------------------------
# PhpProject - Nginx 1.17
# Imagem oficial (Docker Hub): https://hub.docker.com/_/nginx
# Imagem oficial (Git Hub): https://github.com/nginxinc/docker-nginx
#-------------------------------------------------------------------------------------

FROM mysql:8

RUN mkdir -p /application

WORKDIR /application

ENV MYSQL_ROOT_PASSWORD devel
ENV MYSQL_ROOT_PASSWORD devel
ENV MYSQL_DATABASE devel
ENV MYSQL_USER devel
ENV MYSQL_PASSWORD devel

CMD ["mysqld"]
