version: "3.1"
services:
  nginx:
    image: local/docker-project:nginx119
    container_name: test-project-nginx
    volumes:
      - .:/application
    ports:
      - "1000:80"
    networks:
      - dev-network

  php-fpm:
    image: local/docker-project:php80
    container_name: test-project-php
    volumes:
      - .:/application
    networks:
      - dev-network

  composer:
    image: local/docker-project:composer20
    container_name: test-project-composer
    volumes:
      - ./project:/application
    command: composer install --ignore-platform-reqs
    networks:
      - dev-network

  mysql:
    image: local/docker-project:mysql80
    container_name: test-project-mysql
    restart: always
    ports:
      - "2000:3306"
    networks:
      - dev-network

  mariadb:
    image: local/docker-project:mariadb105
    container_name: test-project-mariadb
    restart: always
    ports:
      - "2001:3306"
    networks:
      - dev-network

  percona:
    image: local/docker-project:percona80
    container_name: test-project-percona
    restart: always
    ports:
      - "2001:3306"
    networks:
      - dev-network

  postgres:
    image: local/docker-project:postgres13
    container_name: test-project-postgres
    restart: always
    ports:
      - "2002:8080"
    networks:
      - dev-network

  phpmyadmin:
    image: local/docker-project:phpmyadmin51
    container_name: test-project-phpmyadmin
    restart: always
    depends_on: 
      - mysql
    ports:
      - 3000:80
    networks:
      - dev-network

  riak-kv:
    image: local/docker-project:riakkv22
    container_name: test-project-riakkv
    ports:
      - "4000:8087"
      - "4001:8098"
    networks:
      - dev-network

  zookeeper:
    image: local/docker-project:zookeeper35
    container_name: test-project-zookeeper
    ports:
      - 4005:2181
      - 4006:2000
    networks:
      - dev-network

  kafka:
    image: local/docker-project:kafka27
    container_name: test-project-kafka
    depends_on:
      - zookeeper
    ports:
      - 4007:9092
    networks:
      - dev-network

  kafdrop:
    image: local/docker-project:kafdrop327
    container_name: test-project-kafdrop
    depends_on:
      - kafka
    ports:
      - 5000:9000
    networks:
      - dev-network

  rabbitmq:
    image: local/docker-project:rabbitmq38
    container_name: test-project-rabbitmq
    ports:
      - 6001:5672
      - 6002:15672
    networks:
      - dev-network
    
networks:
  dev-network:
    driver: bridge
