version: "3.1"
services:
  nginx:
    image: local/php-project:nginx119
    container_name: test-project-nginx
    volumes:
      - ./project:/application
    ports:
      - "1000:80"
    networks:
      - dev-network

  php-fpm:
    image: local/php-project:php80
    container_name: test-project-php
    volumes:
      - ./project:/application
    networks:
      - dev-network

  composer:
    image: local/php-project:composer20
    container_name: test-project-composer
    volumes:
      - ./project:/application
    command: composer install --ignore-platform-reqs
    networks:
      - dev-network

  mysql:
    image: local/php-project:mysql80
    container_name: test-project-mysql
    restart: always
    ports:
      - "1010:3306"
    networks:
      - dev-network

  phpmyadmin:
    image: local/php-project:phpmyadmin51
    container_name: test-project-phpmyadmin
    restart: always
    depends_on: 
      - mysql
    ports:
      - 1020:80
    networks:
      - dev-network

  rabbitmq:
    image: local/php-project:rabbitmq38
    container_name: test-project-rabbitmq
    ports:
      - 1030:5672
      - 1040:15672
    networks:
      - dev-network

  riak-kv:
    image: local/php-project:riakkv223
    container_name: test-project-riakkv
    ports:
      - "1050:8087"
      - "1060:8098"
    networks:
      - dev-network

  zookeeper:
    image: local/php-project:zookeeper35
    container_name: test-project-zookeeper
    ports:
      - 1070:2181
      - 1080:2000
    networks:
      - dev-network

  kafka:
    image: local/php-project:kafka27
    container_name: test-project-kafka
    depends_on:
      - zookeeper
    ports:
      - 1090:9092
    networks:
      - dev-network

  kafdrop:
    image: local/php-project:kafdrop327
    container_name: test-project-kafdrop
    depends_on:
      - kafka
    ports:
      - 2000:9000
    networks:
      - dev-network
    
networks:
  dev-network:
    driver: bridge
