#-------------------------------------------------------------------------------------
# PhpProject - PhpMyADMIN 5.1
# Imagem oficial (Docker Hub): https://hub.docker.com/_/phpmyadmin
#-------------------------------------------------------------------------------------

FROM phpmyadmin:5.1-apache

ENV PMA_USER devel
ENV PMA_PASSWORD devel

