version: "3.9"
services:
  java:
    image: ricardopedias/docker-project:java15
    container_name: java-teste
    working_dir: /application
    volumes:
      - ./build/libs:/usr/local/tomcat/webapps
      - ./:/application
    ports:
      - "8888:8080"
  
